import {
  Box,
  Button,
  Flex,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Text,
  Textarea,
  color,
} from "@chakra-ui/react";
import { px } from "framer-motion";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Formulário com NextJs e Chakra-ui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          minHeight="100vh"
          width="full"
          align="center"
          justifyContent="center"
          bgGradient="linear(to-t, purple.300, purple.400, purple.500, purple.700)"
        >
          <Box
            px={12}
            py={12}
            marginTop="20px"
            marginBottom="20px"
            width="full"
            maxWidth="300px"
            textAlign="center"
            bgGradient="linear(to-t, purple.300, purple.400, purple.500, purple.600,)"
            borderRadius="6px"
            boxShadow="dark-lg"
          >
            <Heading>
              <Text color="gray.200" marginBottom="20px" fontSize="2xl">
                Formulário
              </Text>
            </Heading>
            <Box>
              <form action="">
                <Flex justify="space-between">
                  <FormControl flex="1" marginRight="2">
                    <FormLabel color="gray.200">Nome</FormLabel>
                    <Input
                      type="text"
                      name="name"
                      outline="none"
                      focusBorderColor="purple.100"
                    />
                  </FormControl>
                  <FormControl flex="1">
                    <FormLabel color="gray.200">Sobrenome</FormLabel>
                    <Input
                      type="text"
                      outline="none"
                      focusBorderColor="purple.100"
                    />
                  </FormControl>
                </Flex>
                <FormControl>
                  <FormLabel color="gray.100" marginTop="10px">
                    E-mail
                  </FormLabel>
                  <Input
                    type="text"
                    outline="none"
                    focusBorderColor="purple.100"
                  />
                </FormControl>
                <Flex justify="space-between">
                  <FormControl flex="1" marginRight="2">
                    <FormLabel color="gray.200" marginTop="10px">
                      Endereço
                    </FormLabel>
                    <Input
                      type="text"
                      outline="none"
                      focusBorderColor="purple.100"
                    />
                  </FormControl>
                  <FormControl flex="1">
                    <FormLabel color="gray.200" marginTop="10px">
                      Celular
                    </FormLabel>
                    <Input
                      type="text"
                      outline="none"
                      focusBorderColor="purple.100"
                    />
                  </FormControl>
                </Flex>
                <FormControl>
                  <FormLabel color="gray.200" marginTop="10px">
                    Mensagem de descrição
                  </FormLabel>
                  <Textarea resize="none" focusBorderColor="purple.100" />
                </FormControl>
                <Button
                  type="submit"
                  marginTop="20px"
                  width="full"
                  bgColor="purple.300"
                  color="gray.200"
                  boxShadow="dark-lg"
                  _hover={{ color: "blue.50" }}
                >
                  Fazer Cadastro
                </Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  );
}
